// source: user_position.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.UserPosition.UserPositionList', null, global);
goog.exportSymbol('proto.UserPosition.UserPositionReq', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserPosition.UserPositionReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UserPosition.UserPositionReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserPosition.UserPositionReq.displayName = 'proto.UserPosition.UserPositionReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserPosition.UserPositionList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.UserPosition.UserPositionList.repeatedFields_, null);
};
goog.inherits(proto.UserPosition.UserPositionList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserPosition.UserPositionList.displayName = 'proto.UserPosition.UserPositionList';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserPosition.UserPositionReq.prototype.toObject = function(opt_includeInstance) {
  return proto.UserPosition.UserPositionReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserPosition.UserPositionReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserPosition.UserPositionReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    log: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lat: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserPosition.UserPositionReq}
 */
proto.UserPosition.UserPositionReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserPosition.UserPositionReq;
  return proto.UserPosition.UserPositionReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserPosition.UserPositionReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserPosition.UserPositionReq}
 */
proto.UserPosition.UserPositionReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLog(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserPosition.UserPositionReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserPosition.UserPositionReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserPosition.UserPositionReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserPosition.UserPositionReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getLog();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLat();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.UserPosition.UserPositionReq.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserPosition.UserPositionReq} returns this
 */
proto.UserPosition.UserPositionReq.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 log = 2;
 * @return {number}
 */
proto.UserPosition.UserPositionReq.prototype.getLog = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserPosition.UserPositionReq} returns this
 */
proto.UserPosition.UserPositionReq.prototype.setLog = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 lat = 3;
 * @return {number}
 */
proto.UserPosition.UserPositionReq.prototype.getLat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserPosition.UserPositionReq} returns this
 */
proto.UserPosition.UserPositionReq.prototype.setLat = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.UserPosition.UserPositionList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserPosition.UserPositionList.prototype.toObject = function(opt_includeInstance) {
  return proto.UserPosition.UserPositionList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserPosition.UserPositionList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserPosition.UserPositionList.toObject = function(includeInstance, msg) {
  var f, obj = {
    userspositionsList: jspb.Message.toObjectList(msg.getUserspositionsList(),
    proto.UserPosition.UserPositionReq.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserPosition.UserPositionList}
 */
proto.UserPosition.UserPositionList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserPosition.UserPositionList;
  return proto.UserPosition.UserPositionList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserPosition.UserPositionList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserPosition.UserPositionList}
 */
proto.UserPosition.UserPositionList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UserPosition.UserPositionReq;
      reader.readMessage(value,proto.UserPosition.UserPositionReq.deserializeBinaryFromReader);
      msg.addUserspositions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserPosition.UserPositionList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserPosition.UserPositionList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserPosition.UserPositionList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserPosition.UserPositionList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserspositionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.UserPosition.UserPositionReq.serializeBinaryToWriter
    );
  }
};


/**
 * repeated UserPositionReq usersPositions = 1;
 * @return {!Array<!proto.UserPosition.UserPositionReq>}
 */
proto.UserPosition.UserPositionList.prototype.getUserspositionsList = function() {
  return /** @type{!Array<!proto.UserPosition.UserPositionReq>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.UserPosition.UserPositionReq, 1));
};


/**
 * @param {!Array<!proto.UserPosition.UserPositionReq>} value
 * @return {!proto.UserPosition.UserPositionList} returns this
*/
proto.UserPosition.UserPositionList.prototype.setUserspositionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.UserPosition.UserPositionReq=} opt_value
 * @param {number=} opt_index
 * @return {!proto.UserPosition.UserPositionReq}
 */
proto.UserPosition.UserPositionList.prototype.addUserspositions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.UserPosition.UserPositionReq, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.UserPosition.UserPositionList} returns this
 */
proto.UserPosition.UserPositionList.prototype.clearUserspositionsList = function() {
  return this.setUserspositionsList([]);
};


goog.object.extend(exports, proto.UserPosition);
